- .github/workflows/ci.yml
- .gitlab-ci.yml
- target/common/common.mk
- target/snitch_cluster/Makefile
- util/simutils.py
Contains various general fixes:
- simutils.py: Capture missing binary error and print also successful tests
- gitlab-ci: Fix path to run.py for tests
- update `target/snitch_cluster/Makefile` `clean` targets
- bender: Move `VSIM_SOURCES`, `VLT_SOURCES` depending on bender target from `common.mk` to `target/snitch_cluster/Makefile`
- gitlab-ci: Fix VCS target dependency such that the required files inside the `generated` directory are actually generated before the compilation
- sw: add runtime compilation for Banshee to github CI
> ci: Fix Makefile target dependencies and extend simutils.py

- target/snitch_cluster/sw/runtime/rtl/src/putchar.c
- target/snitch_cluster/sw/runtime/rtl/src/snrt.c
- target/snitch_cluster/sw/runtime/rtl/src/snrt.h
- target/snitch_cluster/sw/tests/passing-apps.list
Add lost RTL runtime `putchar` implementation and add `simple_printf` test.
**Attention**: The test does currently not check the actual printed results after the simulation!!!
> printf: Fix printf support for new runtime

- target/snitch_cluster/README.md
Ten cores was legacy from single-cluster Occamy. Here we have only nine cores.
> tutorial: Correct layout file

- .github/workflows/lint.yml
As our linting action takes the "latest" flake8 version by default, CI runs may produce different outcomes if flake8 is updated in the meantime. This may lead to discrepancies between the outcome of the CI on a PR, and the CI on main after merging the PR.
This PR addresses this issue by fixing the flake8 version used by our linting action to the last version which yielded a passing CI status.
> ci: Fix flake8 version

- util/container/Dockerfile
Switch to `bender` version 0.27.1 to use `bender vendor`
> docker: update container

- sw/blas/gemm/src/gemm.h
- target/snitch_cluster/sw/toolchain.mk
This targets the work-in-progress occamy branch, *not* `main`.
Make software build system work with LLVM versions other than 12.0.1 by:
* Making LLVM lib paths adaptive to the version used
* Fixing GNU C language violations in `gemm.h`: `register` may not be used with arrays (this was never legal to begin with, but the frontend lets it slide and the backend only fatals if it actually attempts to map registers)
> sw: Make compatible with non-12 LLVM versions

- .github/workflows/ci.yml
- .github/workflows/publish-docs.yml
- .gitignore
- .gitlab-ci.yml
- Bender.yml
- Makefile
- docs/rm/peripherals.md
- docs/ug/documentation.md
- hw/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson
- mkdocs.yml
Generates documentation for the Snitch cluster peripheral registers, including the performance counters, from the respective `.hjson` description file.
Depends on https://github.com/pulp-platform/register_interface/pull/42, so **wait for it to be merged first and update Bender dependency.**
> docs: Add peripheral registers

- sw/apps/montecarlo/pi_estimation/main.c
- sw/apps/montecarlo/pi_estimation/pi_estimation.h
- sw/apps/prng/lcg.h
- target/snitch_cluster/sw/apps/Makefile
- target/snitch_cluster/sw/apps/montecarlo/pi_estimation/Makefile
- target/snitch_cluster/sw/run.yaml
When merging this we should add the following lines to the end of the commit message:
```
Co-authored-by: Fabio Cappellini <fcappellini@student.ethz.ch>
Co-authored-by: Hakim Filali <hfilali@student.ethz.ch>
```
> sw: Add sample Monte Carlo application

- hw/snitch/src/snitch.sv
- hw/snitch_cluster/src/snitch_cc.sv
- hw/snitch_cluster/src/snitch_cluster.sv
- hw/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
This includes the contributions from #7 and further gates debug features inside the Snitch core with parameters, controlled by the existing `debug_enable` configuration key:
* It adds software RW to the `dcsr`, `dpc`, and `dscratch0` registers.
* It disables the instantiation of any debug registers, and thus logic through constant propagation, when `debug_enable` is 0.
> hw: Improve debug parameterization, fix debug CSR RW

- target/snitch_cluster/Makefile
This PR changes the LRU config file mechanism in the following way.
The LRU config file becomes a symlink, pointing to the `cfg/default.hjson` config file by default. Upon an override request (using the `CFG_OVERRIDE` flag) the symlink is updated to point to the requested config file. This is in contrast to the previous implementation, where the LRU config file was a regular file, and the contents of the default or overridden config files were copied into it.
This change allows the following behaviour. If the config file which the LRU config points to changes, any Make target depending on the LRU config will be updated. So you don't have to update the LRU config file contents, but can directly update the original config file (which is now the target of the symlink).
> target: Update LRU config mechanism

- target/common/test/verilator_lib.cc
Fixes #57 
Currently, Verilator relies on the global function `sc_time_stamp` to implement the `$time` function in verilog. `$time` is used by the simulator's trace and the performance tooling in the repo to track performance. However, although the current implementation of the testbench increments the time counter on each cycle, it is still dividing this time counter by `1e9`. With the default assumption of 1 cycle taking 1ns and time precision of 1ps, this would imply that we are representing the `sim::TIME` variable as being in attoseconds (`1e18 attoseconds = 1 second`). This PR instead scales the time variable to return the expected picosecond precision. 
Reference example from Verilator 4.100 where no multiplication by `1e-9` takes place: …
> target/common: Scale verilator testbench time precision as picoseconds

- target/common/test/ipc.cc
When using the `verification.py` library and `SnitchSim` to run a simulation then read results from the kernel execution, the IPC thread will crash the whole program once SnitchSim has finished issuing the read commands. This is because the current check for EOF in `ipc.cc` erroneously checks for EOF before the `fread` attempt, instead of after the `fread` attempt. See the following StackOverflow for how this is usually corrected:
https://stackoverflow.com/questions/5431941/why-is-while-feoffile-always-wrong
Because of this erroneous check, the last operation (which is usually a read memory operation) will be doubly executed, causing the attempt to write to and flush `rx` to fail, since `SnitchSim.py` will have already closed the pipe and directory. As such, the program crashes and the …
> target/common: Fix dasm traces truncation when using SnitchSim

- sw/snRuntime/src/dump.h
- Defines a single macro to define named dump functions for any variable type (no need for separate `dump_float`, `dump_int`, etc)
- Defines a `DUMP` macro to conveniently dump any value, through a pre-defined CSR
> snRuntime: Update `dump.h` routines

- Bender.yml
- hw/snitch_cluster/src/snitch_cc.sv
- hw/snitch_cluster/src/snitch_fp_ss.sv
- hw/snitch_cluster/src/snitch_fpu.sv
- sw/blas/gemm/src/gemm.h
- sw/blas/gemm/src/main.c
- target/snitch_cluster/cfg/default.hjson
- target/snitch_cluster/sw/apps/common.mk
- target/snitch_cluster/sw/toolchain.mk
This PR removes an IF statement preventing from running low precision FP GEMM. 
The FP latencies in the snitch cluster default configuration are aligned with the Occamy configuration.
The FPU is bumped to the latest version `pulp-v0.1.3`.  The hart_id is propagated to the FPUs. The hart_id is used to initialize the seed of the LFSR used for stochastic rounding in each of the wDotp modules.
The SW check on the GEMM results has been modified to consider relative errors.
> hw: Bump FPU, update FP latencies, fix low-precision FP GEMM

- Makefile
- apt-requirements.txt
- docs/requirements.txt
- docs/rm/sim/Simulation.md
- docs/rm/sim/Simulator.md
- docs/rm/sim/sim_utils.md
- mkdocs.yml
- target/common/common.mk
- target/snitch_cluster/Makefile
- target/snitch_cluster/run.py
- target/snitch_cluster/sw/run.yaml
- util/container/Dockerfile
- util/sim/Simulation.py
- util/sim/Simulator.py
- util/sim/sim_utils.py
> Extend simulation utilities

- sw/snRuntime/src/sync.h
An additional `snrt_cluster_hw_barrier` is required before the DM cores synchronize. 
Currently, the DM cores do not know if the other compute cores have arrived at the barrier. For example if a compute core in cluster 0 is late arriving at the barrier, other clusters will not wait for this core.
> `snrt_global_barrier` requires additional `snrt_cluster_hw_barrier`

- sw/snRuntime/api/sync_decls.h
- sw/snRuntime/src/start.c
- sw/snRuntime/src/sync.c
- sw/snRuntime/src/sync.h
- sw/tests/event_unit.c
- sw/tests/fp16_comparison_scalar.c
- sw/tests/fp16_comparison_vector.c
- sw/tests/fp16_computation_scalar.c
- sw/tests/fp16_computation_vector.c
- sw/tests/fp16alt_comparison_scalar.c
- sw/tests/fp16alt_comparison_vector.c
- sw/tests/fp16alt_computation_scalar.c
- sw/tests/fp16alt_computation_vector.c
- sw/tests/fp32_comparison_scalar.c
- sw/tests/fp32_comparison_vector.c
- sw/tests/fp32_computation_scalar.c
- sw/tests/fp32_computation_vector.c
- sw/tests/fp32_conversions_scalar.c
- sw/tests/fp64_conversions_scalar.c
- sw/tests/fp8_comparison_scalar.c
- sw/tests/fp8_comparison_vector.c
- sw/tests/fp8_computation_scalar.c
- sw/tests/fp8_computation_vector.c
- sw/tests/fp8alt_comparison_scalar.c
- sw/tests/fp8alt_comparison_vector.c
- sw/tests/fp8alt_computation_scalar.c
- sw/tests/fp8alt_computation_vector.c
- sw/tests/team_global.c
- target/snitch_cluster/sw/run.yaml
> `snRuntime`: Extend exit function with reduction

- util/trace/gen_trace.py
Fixes a tracer bug wherein having multiple instructions in an `frep.i` body crashes it  due to an empty-pop.
> util: Fix multi-instruction `frep.i` tracing

- sw/blas/gemm/src/gemm.h
- sw/blas/gemm/verify.py
To compare the performance of the `Xssr` and `Xfrep` extensions, this PR adds baseline (optimized) GEMM kernels.
> sw: Add GEMM baselines without SSR & frep extensions

- target/snitch_cluster/cfg/default.hjson
- target/snitch_cluster/cfg/fdiv.hjson
- target/snitch_cluster/cfg/omega.hjson
Before merging https://github.com/pulp-platform/snitch_cluster/pull/94, we did not rebase manually on main. Before it, we merged https://github.com/pulp-platform/snitch_cluster/pull/52, which added the `alias` test which went untested in the CI of https://github.com/pulp-platform/snitch_cluster/pull/94. Indeed, that test does not pass because the configuration file for the Snitch cluster with Omega network does not enable aliasing.
This PR fixes this. Additionally it introduces some minor changes to the syntax of the configuration files, to transition towards json5 in place of hjson.
> cfg: Fix OmegaNet configuration for alias test

- sw/dnn/conv2d/src/conv2d.h
- target/common/common.mk
- util/trace/annotate.py
> Move towards LLVM 15 toolchain

- .github/workflows/ci.yml
- .gitignore
- .gitlab-ci.yml
- docs/ug/getting_started.md
- iis-setup.sh
- target/common/common.mk
- target/snitch_cluster/Makefile
- util/container/Dockerfile
- util/sim/Simulation.py
Add Snitch ISA aware `riscv-isa-sim` version as submodule. Only used for `spike-dasm` to make the generated traces more readable.
In the old `snitch` repository it was flattened (without `vendor`) from the [repository](https://github.com/huettern/riscv-isa-sim) of @huettern. The branch was ported to the [pulp-platform repository](https://github.com/pulp-platform/riscv-isa-sim/tree/GiannaP-snitch).
> spike-dasm: Add Snitch ISA aware riscv-isa-sim as submodule

- target/common/test/SnitchSim.py
If the `SnitchSim` instance is waiting on a `read()` from the pipe to the simulation, and the RTL simulation terminates prematurely (e.g. due to a fatal assertion failure), the `SnitchSim` instance would block on the `read()` and any verification script based on it would not terminate.
When the simulation subprocess is spawned, a separate thread is created to monitor it. If the simulation terminates prematurely, the monitor will notice and send a `SIGINT` signal to interrupt the `read()`. The signal is handled by the main thread which will stop the simulation monitor, communicate the cause of the failure and gracefully terminate the verification script.
> ipc: Handle failing RTL simulations

- target/common/common.mk
- target/common/test/tb_bin.cc
- target/common/vsim.mk
- target/snitch_cluster/Makefile
> target: Improve reusability of Questa Make targets

- .gitignore
- .gitlab-ci.yml
- Makefile
Adds the `make nonfree` target to clone the non-free repository, and extends the CI to run non-free elaboration job.
> treewide: Add nonfree directory and CI jobs

- sw/blas/gemm/src/gemm.h
- sw/dnn/flashattention_2/verify.py
- target/snitch_cluster/sw/fdiv.yaml
The FP32 baseline implementation of the GEMM causes significant errors in the FlashAttention-2 kernel. Hence, it has been replaced by the naive FP32 kernel, which yields the correct results.
> FlashAttention-2 fix

- sw/blas/axpy/data/params.json
- target/common/vsim.mk
- target/snitch_cluster/Makefile
This adds a `clean` target for the VSIM Makefile for compatibility with the Occamy `make clean` target.
> common: Add `clean-vsim` target and align AXPY to Occamy

- sw/snRuntime/api/alloc_decls.h
- sw/snRuntime/api/cls_decls.h
- sw/snRuntime/api/cluster_interrupt_decls.h
- sw/snRuntime/api/global_interrupt_decls.h
- sw/snRuntime/api/memory_decls.h
- sw/snRuntime/api/omp/eu_decls.h
- sw/snRuntime/api/riscv_decls.h
- sw/snRuntime/api/start_decls.h
- sw/snRuntime/api/sync_decls.h
- sw/snRuntime/api/team_decls.h
- sw/snRuntime/src/alloc.h
- sw/snRuntime/src/cls.h
- sw/snRuntime/src/cluster_interrupts.h
- sw/snRuntime/src/dma.h
- sw/snRuntime/src/dump.h
- sw/snRuntime/src/global_interrupts.h
- sw/snRuntime/src/perf_cnt.h
- sw/snRuntime/src/printf.h
- sw/snRuntime/src/riscv.c
- sw/snRuntime/src/riscv.h
- sw/snRuntime/src/ssr.h
- sw/snRuntime/src/start.c
- sw/snRuntime/src/sync.h
- sw/snRuntime/src/team.h
- target/snitch_cluster/sw/runtime/banshee/src/snrt.c
- target/snitch_cluster/sw/runtime/rtl/src/snrt.c
Downstream projects wishing to use the snitch runtime via its `*_decls` headers have so far run into a few issues:
* Not all headers correctly include the C standard headers of entities they depend on
* There were no header guards or similar present, making multiple includes an error in many cases
This PR fixes these issues by:
* `#include`ing required headers
* Adding `#pragma once` to all headers
As a further drive-by, the riscv_decls.h header was fixed to be usable without linking errors the same way as other files
> sw: Adjust `*_decls` headers for usability in downstream projects

- util/sim/sim_utils.py
Addresses a possible race condition for which, from the moment living subprocesses are listed and killed, new subprocesses could be spawned, which would never be killed.
This solution provides a remedy so long as this race condition doesn't occur 10 times in a row. Note that it does not fundamentally solve the problem, but even if subprocesses might still be leaked, the leakage rate should be acceptable.
> util/sim: Robustify subprocess termination

- sw/snRuntime/src/openocd.h
- sw/snRuntime/src/start.c
- target/snitch_cluster/README.md
- target/snitch_cluster/sw/runtime/rtl/src/putchar.c
- target/snitch_cluster/sw/runtime/rtl/src/snitch_cluster_start.c
- target/snitch_cluster/sw/toolchain.mk
This adds a SELECT_PLATFORM option which can be used to compile the runtime for GVSOC.
This will then select a dedicated putchar which is using OpenOCD semi-hosting. This is also used for exit.
This is used to avoid the polling in dram due to htif modeling, which disturbs dram timing model with extra page misses.
This also fixes an uninitialized access to putchar index which fails on gvsoc since memory is not initialized to zero.
> sw: Add possibility to get ocd putchar on gvsoc

- sw/snRuntime/src/alloc.c
- sw/snRuntime/src/cls.c
- sw/snRuntime/src/sync.c
- sw/snRuntime/src/team.c
Adds more `extern` declarations to https://github.com/pulp-platform/snitch_cluster/pull/133.
> snRuntime: Fix inline function definitions missing in static library

- target/common/test/tb_bin.cc
- target/common/test/tb_lib.hh
- target/common/test/verilator_lib.cc
Building the snitch verilator model on distros using musl libc is currently not possible due to some glibc specific assumption and a musl libc peculiarly. More specifically, code was using `#include <printf.h>` instead of `#include <stdio.h>` which is a glibc specific header. Lastly, `PAGE_SIZE` is a macro provided by Linux headers that expands to a number. musl libc unfortunately indirectly includes it via `#include <limit.h>`. Renaming occurrences of `PAGE_SIZE` fixes the name clash.
> target: Allow verilator build with musl libc

- util/sim/sim_utils.py
Killing a process can indirectly cause another process to terminate. Therefore, a previously listed living subprocess may not exist anymore when we attempt to kill it, raising a `ProcessLookupError` exception.
This PR addresses this issue, by handling any `ProcessLookupError` which may arise in this setting, simply ignoring it.
> util/sim: Handle `ProcessLookupError` in subprocess termination

- Bender.yml
- hw/snitch_cluster/src/snitch_tcdm_interconnect.sv
https://github.com/pulp-platform/common_cells/pull/200, recently included by a dependency update, may trigger false-positive TCDM stability assertion errors in some cases when using SSRs.
This is because SSR write data is hardwired to the bidirectional data FIFO output. Therefore, on reads, the write data bits may change irrespective of when a read request is pending. This instability is benign, but causes the payload-wide assertion to fail.
This PR, together with https://github.com/pulp-platform/common_cells/pull/219, fixes this issue by masking stability assertion on the write data and mask inside `stream_xbar` and `stream_omega_net` and then conditionally asserting write data and mask stability on reads and atomics in `snitch_tcdm_interconnect`.
A more general discussion is maybe in …
> hw: Mask TCDM write data stability check on reads

- python-requirements.txt
This adds two Python packages to the `python-requirements.txt`:
1. `humanzie`
2. `json5`
For the new data generation and visualization scripts that will be introduced partly in #137 .
This commit must be merged **BEFORE** #137 to rebuild the docker image on `main`.
> docker: update packages

- .github/workflows/ci.yml
- Bender.yml
- sw/snRuntime/src/alloc.h
- sw/snRuntime/src/dma.h
- sw/snRuntime/src/start.c
Implements the changes discussed in https://github.com/pulp-platform/snitch_cluster/pull/153 which were waiting for a new release of the iDMA containing the mentioned bug fix.
As collateral efforts required to merge this, we:
- fix a synchronization bug in the snRuntime
- fix a bug in the Github CI
> treewide: Bump iDMA and update handling of zero-length transfers

- util/container/Dockerfile
Fixes Banshee installation in our Docker container. See https://github.com/pulp-platform/banshee/pull/19 for more info.
> container: Fix Banshee installation

- util/sim/Simulation.py
Some spurious behaviour in Banshee caused the simulation traces to take up GBs of space on our internal CI servers, as reported by @Xeratec.
As the Banshee traces are not used in any way, this PR disables trace logging in Banshee, which will anyways hopefully be replaced by GVSoC sometime soon.
> util: Disable Banshee simulation traces

- sw/snRuntime/base.ld
- target/snitch_cluster/sw/runtime/rtl/src/putchar.c
This PR introduces two fixes to the Snitch runtime that are required for Deeploy.
The first issue is related to the location of the `snrt_l1_allocator()` which is calculated via the `cls()` function. This function uses the `_cls_ptr` which is placed at the beginning of the `.cbss` section. However, if the `.cbss` section is empty, this location is invalid.
The second fix statically allocated the buffers for multicore compatible `printf()` function. Without this fix, the buffers overlap with the L3 allocator, causing `printf()` call to overwrite the allocation structure.
- Ensure the `.cbss` section is not optimized away.
-  Statically allocate `printf()` buffers
> sw: Runtime Fixes

- .gitignore
- Bender.local
- Bender.lock
- Bender.yml
- hw/snitch_cluster/src/snitch_cc.sv
- target/common/common.mk
A new AXI patch release broke the Gitlab-CI, and bender automatically incremented the AXI version since we don't have a `Bender.lock` file tracked that locks the IP versions used. To prevent similar problems in the future and to give users of the snitch cluster a clear set of dependency versions I suggest to track the `Bender.lock` file.
Apart from that, this PR does also:
* Bump the AXI version
* Remove the `Bender.local` file, which is redundant now and is anyway more of a hack.
* Fixes some minor issues for VCS simulation that were somehow triggered only after updating the dependencies.
> deps: Track `Bender.lock` file

- Bender.yml
The axi **vcs-fixes** branch has been merged into the **master** branch some days ago.
The [Bender file](https://github.com/pulp-platform/snitch_cluster/blob/4f55f01ffa4e99421af1b71b5bbbf867faf692bf/Bender.yml#L22) is still trying to point to that branch.
I change the revision to the last [axi commit](https://github.com/pulp-platform/axi/commit/4e54ac6766b160217a83a74d5a23af9bbf59e6ee).
> Fix axi dependency in Bender

- target/common/common.mk
- util/bench/visualize.py
- util/sim/Simulation.py
- util/sim/sim_utils.py
- util/trace/a2l.py
- util/trace/annotate.py
- util/trace/gen_trace.py
- util/trace/tracevis.py
- The simulation time would be taken from the first line printing the time, this included error messages. We fix this by taking the last line printing the time.
- We use the `PrettyTable` title feature to replace our custom title output for the test summary table.
- Dry simulation runs do not produce any log file. We should not attempt to read the return code from the log file when the run is dry.
- Add column field to annotated simulation traces. This is possible only with LLVM toolchains, so we must handle GCC and LLVM toolchains differently.
- Previously, lines without timestamps, e.g. FPU instructions executed in the same cycle as an integer instruction, were being parsed incorrectly, so they would not be annotated. Now we use a regex to handle these lines properly.
- Fix …
> util: Extend simulation and trace utilities

- sw/snRuntime/src/dma.h
The inline assembly uses `t1` both as input operand (via the `cfg` variable) and within the clobber list. This is illegal but due to a bug in clang 12 that has been fixed in clang 14 has gone unnoticed. Quoting from the GCC documentation (https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#Clobbers-and-Scratch-Registers-1):
> Clobber descriptions may not in any way overlap with an input or output operand. For example, you may not have an operand describing a register class with one member when listing that register in the clobber list. Variables declared to live in specific registers (see Variables in Specified Registers) and used as asm input or output operands must have no part mentioned in the clobber description.
This correctly emits an error if using Clang 14 or any version of GCC: …
> sw: Fix invalid inline assembly in `snrt_dma_wait_channel`

- .github/workflows/ci.yml
- .github/workflows/lint.yml
- .gitlab-ci.yml
- Bender.lock
- Bender.yml
- Makefile
- iis-setup.sh
- target/snitch_cluster/Makefile
Fixes and enables again the elaboration flow thanks to some [upstream changes](https://github.com/pulp-platform/iDMA/pull/52/commits/9cbcd3085a1881aa46806ca61a5053b86e9c9562) in the iDMA repo. Also revert back generation of DMA sources, which are automatically included in the `__deeploy__` branches
> ci: Fix elaboration flow

- iis-setup.sh
- target/common/common.mk
- target/snitch_cluster/Makefile
- util/trace/gen_trace.py
For trace generation we currently use `spike-dasm` to dissassemble single instructions from core log files. The problem with `spike-dasm` is that is an external executable, that needs to be maintained by us. For instance, new instructions need to be added manually to `spike-dasm` for decoding.
The better alternative is [`llvm-mc`](https://llvm.org/docs/CommandGuide/llvm-mc.html) which is a CLI tool that is compiled alongside LLVM. This means all our custom ISA extensions supported by the LLVM toolchain are also automatically supported by `llvm-mc`  and don't have to be added manually to the dissasembler as before.
> util: Replace `spike-dasm` in favor of `llvm-mc`

- hw/snitch/src/snitch.sv
- Add misaligned address to the error message presented upon misaligned load/stores.
- Replace `$display` system function with `$info`, which already includes the timestamp as well as additional info, for misaligned load/stores and illegal instruction messages.
> hw: Add debug information to error messages

- target/snitch_cluster/test/testharness.sv
- target/snitch_cluster/test/vip_snitch_cluster.sv
- util/container/Dockerfile
Revert the testbench clock period back to 1ns from 10ns, after it was unadvertedly changed with #168.
This PR was split from https://github.com/pulp-platform/snitch_cluster/pull/204, see discussion thereof for more details.
> target: Fix testbench clock period regression from #168

- .github/workflows/gitlab-ci.yaml
- .gitlab-ci.yml
- The internal Gitlab CI job in the Github CI was run on both the pull request and the push trigger, which both occur when pushing to a pull request from the same repository. We avoid these duplicate runs by disabling the pull request trigger.
- Previously, every job in the Gitlab CI was creating a virtual environment and installing corresponding dependencies. This likely favoured the occurrence of "Out of disk space" errors. Now we run a "setup" job at the beginning, and store the pip cache as an artifact. All other jobs depend on this job, so they will inherit the installed cache folder, and the `iis-setup.sh` script does not need to download all the packages again. Caching the virtual environment entirely has been avoided as virtual environments are theoretically not relocatable.
> Improve CI

- .github/workflows/ci.yml
This PR implements two **contributions**:
- Replace slashes with hyphens in Github ref names, to comply with Docker tag naming requirements.
- Disable main workflow runs on pull requests.
The second is motivated by pull requests from forks not being able to deploy the Docker container on this repo. This seems to be due to missing `GITHUB_TOKEN` **permissions**. It also doesn't seem to be possible to use the `pull_request_target` trigger to this end. Nonetheless, the workflow can still be run on the fork itself.
While the Docker container could also just be built and tested in the CI run, without requiring access to secrets, this leads to a lot of **boilerplate** code.
Our **solution** going forward is to simply ask contributors to enable the CI on their public fork, so that the …
> ci: Enable pull requests from forks

- docs/rm/hw/custom_instructions.md
There was the wrong OpCode space specified for the Xfrep extension.
> Fix documentation of Frep instruction encoding

- util/container/Dockerfile
The current docker container is ~12.5GB - a lot of which is nvidia stuff brought in by torch and pip cache. This change modifies the dockerfile to explicitly install the cpu only version of torch and disables the PIP cache to shrink the docker image from 12.5GB to about 4.5GB.
> Eliminate PIP cache and force torch cpu only install

- sw/snRuntime/src/ssr.h
The FPU fence uses a dummy variable to synchronize on the FPU pipeline. This dummy variable is passed to an inline asm block as in/output. In case there are more than one in/output the compiler will allocate the dummy variable to the same register as any other in/output because the unused variable is optimized away. We can ensure a separate register by marking it as volatile.
> sw: Ensure inline asm output register allocation in FPU fence

- target/snitch_cluster/sw/riscv-tests/riscv-tests.mk
Was overriding a similar rule defined by Cheshire in Picobello.
> sw: Reduce scope of `riscv-tests` pattern rule

- hw/snitch_cluster/src/snitch_cluster.sv
- hw/snitch_cluster/src/snitch_cluster_wrapper.sv.tpl
- util/clustergen/schema/snitch_cluster.schema.json
This PR enables support for the exposure of multiple wide TCDM ports, useful if one wants to use multiple external accelerators at the same time.
> Expose multiple wide TCDM ports

- target/common/common.mk
- target/snitch_cluster/util/build.py
The ROI make target used the old `CFG` variable to pass the current hardware configuration.
It seems that this variable has been renamed to `SN_CFG`
> Fix roi target
